package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;
public class UICheckBalanceController {
	@FXML
	private Button bBack;
	@FXML
	private Button bRegisterNewStudent;
	@FXML
	private Button bCheckBalance;

	
	public void initialize(){
		
	}
	// Event Listener on Button[#bBack].onAction
	@FXML
	public void returnMain(ActionEvent event) {
		closeWindows();
	}
	// Event Listener on Button[#bRegisterNewStudent].onAction
	@FXML
	public void registerNewStudent(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/UIRegisterStudent.fxml"));
			Parent root = loader.load();
			UIRegisterStudentController controller = loader.getController();
			controller.initialize();
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			
			stage.setOnCloseRequest(e -> controller.closeWindows());
			Stage temp = (Stage) this.bBack.getScene().getWindow();
			temp.close();
			
		}catch(IOException e){
			
		}
	}
	// Event Listener on Button[#bCheckBalance].onAction
	@FXML
	public void SearchBalance(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void closeWindows() {
		
		try {
			 FXMLLoader loader = new FXMLLoader (getClass().getResource("/presentation/UIStart.fxml"));
	        Parent root = loader.load();
			Scene scene = new Scene(root);
	        scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		
	        Stage stage = new Stage();
	        stage.setScene(scene);
	        stage.show();
	        
	        Stage temp = (Stage) bBack.getScene().getWindow();
	        temp.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
