package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class UILoginController {
	@FXML
	private Button btnRegister;
	@FXML
	private Button btnLogin;

	// Event Listener on Button[#btnRegister].onAction
	@FXML
	public void loginRegister(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void loginAdmin(ActionEvent event) {
		// TODO Autogenerated
	}
}
