package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ToggleGroup;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.control.RadioButton;

public class UIRegisterDishesController {
	@FXML
	private Label lServiceHours;
	@FXML
	private Label lServiceDay;
	@FXML
	private Label lServiceName;
	@FXML
	private Label lServicePrice;
	@FXML
	private RadioButton rbBreakfastDishe;
	@FXML
	private ToggleGroup Tipo;
	@FXML
	private RadioButton rbLunchDishe;
	@FXML
	private ComboBox cbServiceDayDishe;
	@FXML
	private TextField tfServiceNameDishe;
	@FXML
	private TextField tfServicePriceDishe;
	@FXML
	private Label lErrorValidate;
	@FXML
	private Button btnSaveDishe;
	@FXML
	private Button btnBack;

	// Event Listener on RadioButton[#rbBreakfastDishe].onAction
	@FXML
	public void saveBreakfastJSON(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#rbLunchDishe].onAction
	@FXML
	public void saveLunchJSON(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSaveDishe].onAction
	@FXML
	public void saveDataDishe(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBack].onAction
	@FXML
	public void returnMain(ActionEvent event) {
		// TODO Autogenerated
	}
}
